version: '3.8'
services:
  axonserver:
    image: axoniq/axonserver:latest
    hostname: axonserver
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axon

  postgres-read:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  postgres-keycloak:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    networks:
      - keycloak

  keycloak:
    depends_on:
      - postgres-keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak_db
      DB_USER: keycloak_user
      DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    image: keycloak/keycloak:latest
    ports:
      - "18080:8080"
    command:
      - "start-dev"
    networks:
      - keycloak

volumes:
  axonserver-data:
    driver: local

  axonserver-events:
    driver: local

  axonserver-config:
    driver: local

  postgres:

networks:
  axon:
  keycloak: