version: '3.8'
services:
  axonserver:
    image: axoniq/axonserver:2024.0.2
    hostname: axonserver
    environment:
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axon

  postgres-lookup-db:
    container_name: postgres-lookup
    image: postgres:15
    environment:
      POSTGRES_DB: lookup_db
      POSTGRES_USER: lookup_user
      POSTGRES_PASSWORD: lookup_password
    ports:
      - "15432:5432"

  postgres-read:
    container_name: postgres-read
    image: postgres:15
    environment:
      POSTGRES_DB: read_db
      POSTGRES_USER: read_user
      POSTGRES_PASSWORD: read_password
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  postgres-keycloak:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    networks:
      - keycloak

  keycloak:
    depends_on:
      - postgres-keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak_db
      DB_USER: keycloak_user
      DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    image: keycloak/keycloak:23.0.1
    ports:
      - "18080:8080"
    volumes:
      - ./external-realm.json:/opt/keycloak/data/import/external-realm.json
    command: start-dev --import-realm
    networks:
      - keycloak

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-conf:/etc/nginx
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  axonserver-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
  axonserver-events:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/events
      o: bind
  axonserver-config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/config
      o: bind
  postgres:

networks:
  axon:
  keycloak: