spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: password

  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: http://localhost:18080/realms/external

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true


server:
  servlet:
    context-path: /api

jwt:
  expiration:
    time: 3600000

  secret: ${JWT_SECRET:frejjjfiureffwer}
