spring:
  profiles:
    default: read

keycloak:
  url: http://localhost:18080
  external:
    service-client:
      secret: svsrMqyCCb0TZT9ccQS8q8w0ne2YfoJA
    jwks:
      uri: http://localhost:18080/realms/external/protocol/openid-connect/certs
